USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
CREATE OR REPLACE SCHEMA CORTEX_AGENTS_DEMO.FINANCE_FOOD_BEVERAGE;

CREATE OR REPLACE STAGE DOCUMENTS
  DIRECTORY = (ENABLE = TRUE)
  ENCRYPTION = ( TYPE = 'SNOWFLAKE_SSE' );

CREATE OR REPLACE NOTEBOOK SETUP_AGENT_FINANCE_FOOD_BEVERAGE
    FROM '@CORTEX_AGENTS_DEMO.PUBLIC.GITHUB_REPO_CORTEX_AGENTS_DEMO/branches/main/use_cases/nesdata' 
        MAIN_FILE = 'SETUP_AGENT_FINANCE_FOOD_BEVERAGE.ipynb' 
        QUERY_WAREHOUSE = COMPUTE_WH;
ALTER NOTEBOOK SETUP_AGENT_FINANCE_FOOD_BEVERAGE ADD LIVE VERSION FROM LAST;

EXECUTE NOTEBOOK SETUP_AGENT_FINANCE_FOOD_BEVERAGE();